Version: 0.0.1 

Last Updated: 2016-08-22

=== NAME
ScarfXmlReader - A C library for parsing SCARF

=== SYNOPSIS
[source,c]
----
#include <stdio.h>
#include "ScarfXmlReader.c"

int main(int argc, char **argv) {
    ScarfXmlReader *reader = NewScarfXmlReaderFilename("/path/to/file", "UTF-8");
    if(reader == NULL){
        printf("reader failed\n");
        return 1;
    }

    SetInitialCallback(reader, initialFunction);
    SetBugCallback(reader, bugFunction);
    SetMetricCallback(reader, metricFunction);
    SetBugSummaryCallback(reader, bugSummaryFunction);
    SetMetricSummaryCallback(reader, metricSummaryFunction);
    SetFinishCallback(reader, finishFunction);
    
    void *context = DATA;
    SetCallbackData(reader, context);

    Parse(reader);
    DeleteScarfXmlReader(reader);
    return 0;
}
----
=== DESCRIPTION
This library provides the ability to parse SWAMP Common Assessment Results Format (SCARF) XML files into C data structures. It is dependent on libxml, which is used to handle parsing of the XML document.

The parser provides data to the user through the use of user provided callbacks. A callback will be called once the parser is finished parsing a section of the document. These sections are the beginning AnalyzerReport tag, an entire BugInstance or Metric, a complete BugSummary or MetricSummary, and the end AnalyzerReport tag.

All Callbacks except the FinishCallback receive as parameters a pointer to a struct containing information on their section of parsed data and a pointer to the context data passed to SetCallbackData (or NULL if not set). Upon reaching the end of an Analyzer Report the FinishCallback  will be called with the error value returned by the previous call or NULL if there was no error, and if set the context reference set by SetCallbackData.

While the parser does do minor checks to ensure the inputted file is a SCARF file, if an invalid SCARF file is passed in, most behavior is undefined. Additional validation routines can be found in the ScarfXmlWriter library.
=== METHODS
==== ScarfXmlReader *NewScarfXmlReaderFromFilename(char *filename, char *encoding)
Initializes a ScarfXmlReader struct. Opens a file stream from the file represented by the filename to be parsed. The file stream is closed upon completion of the parse. Encoding is the document encoding, such as UTF-8, UTF-16, ISO-Latin-1 (ISO-8859-1), or ASCII (or NULL to use the default of UTF-8).

==== ScarfXmlReader *NewScarfXmlReaderFromString(char *s, char *encoding)
Initializes a ScarfXmlReader struct with s being a NULL terminated string representing the SCARF data to be parsed from memory. Encoding is the document encoding, such as UTF-8, UTF-16, ISO-Latin-1 (ISO-8859-1), or ASCII (or NULL to use the default of UTF-8).

==== ScarfXmlReader *NewScarfXmlReaderFromFd(int fd, char *encoding)
Initializes a ScarfXmlReader struct with the given file descriptor. Encoding is the document encoding, such as UTF-8, UTF-16, ISO-Latin-1 (ISO-8859-1), or ASCII (or NULL to use the default of UTF-8).

==== ScarfXmlReader *NewScarfXmlReaderFromMemory(char *s, int size, char *encoding)
Initializes a ScarfXmlReader struct to parse from memory. s is a initial char pointer and size represents the size in bytes of the document in memory. Encoding is the document encoding, such as UTF-8, UTF-16, ISO-Latin-1 (ISO-8859-1), or ASCII (or NULL to use the default of UTF-8).

==== void SetInitialCallback(ScarfXmlReader *reader, InitialCallback startFunction)
Sets the InitialCallback to be called after each AnalyzerReport start tag is parsed. For details on callbacks see below.

==== void SetBugCallback(ScarfXmlReader *reader, BugCallback bugFunction)
Sets the BugCallback to be called after each full BugInstance is parsed. For details on callbacks see below.    
 
==== void SetMetricCallback(ScarfXmlReader *reader, MetricCallback metricFunction)
Sets the MetricCallback to be called after each full Metric is parsed. For details on callbacks see below.

==== void SetBugSummaryCallback(ScarfXmlReader *reader, BugSummaryCallback bugSummaryFunction)
Sets the BugSummaryCallback to be called after the bug summary data is parsed. For details on callbacks see below.

==== void SetMetricSummaryCallback(ScarfXmlReader *reader, MetricSummaryCallback metricSummaryFunction)
Sets the MetricSummaryCallback to be called after the metric summary data is parsed. For details on callbacks see below. 

==== void SetFinalCallback(ScarfXmlReader *reader, FinalCallback finalFunction) 
Sets the FinalCallback to be called after each AnalyzerReport end tag is parsed. For details on callbacks see below.

==== void SetCallbackData(ScarfXmlReader *reader, void *context) 
Sets the context data to be used as an additional parameter to callbacks. This data is passed to all callbacks and can be used to avoid global variables.

==== InitialCallback GetInitialCallback(ScarfXmlReader *reader) 
Access the current value of InitialCallback. For details on callbacks see below.

==== BugCallback GetBugCallback(ScarfXmlReader *reader) 
Access the current value of BugCallback. For details on callbacks see below.

==== MetricCallback GetMetricCallback(ScarfXmlReader *reader) 
Access the current value of MetricCallback. For details on callbacks see below.

==== BugSummaryCallback GetBugSummaryCallback(ScarfXmlReader *reader) 
Access the current value of BugSummaryCallback. For details on callbacks see below.

==== MetricSummaryCallback GetMetricSummaryCallback(ScarfXmlReader *reader) 
Access the current value of MetricCallback. For details on callbacks see below.

==== FinalCallback GetFinalCallback(ScarfXmlReader *reader) 
Access the current value of FinalCallback. For details on callbacks see below.

==== void *GetCallbackData(ScarfXmlReader *reader) 
Access the current value of CallbackData.

==== void *Parse()
This method initiates the parsing of the XML. If parsing fails an exit(1) call will be thrown. The return value of parse will be the return value of FinalCallback if it is defined. Otherwise the return value will be the same as the last callback executed or NULL if there are no errors.  

==== BugInstance *CopyBug(BugInstance *bug)
Creates a copy of the BugInstance struct and stores it in memory. Returned pointer does not automatically get freed and must be deleted using the corresponding delete method.

==== Metric *CopyMetric(Metric *metric)
Creates a copy of the Metric struct and stores it in memory. Returned pointer does not automatically get freed and must be deleted using the corresponding delete method.

==== Metric *CopyInitial(Initial *init)
Creates a copy of the Initial struct and stores it in memory. Returned pointer does not automatically get freed and must be deleted using the corresponding delete method.

==== void DeleteInitial(Initial *initial)
Frees an Initial struct.

==== void DeleteMetric(Metric *metric)
Frees a Metric struct.

==== void DeleteBug(BugInstance *bug)
Free a BugInstance struct.

==== void DeleteBugSummary(BugSummary *bugSummary)
Frees a BugSummary struct.

==== void DeleteMetricSummary(MetricSummary *metricSummary)
Frees a MetricSummary struct.

==== int DeleteScarfXmlReader(ScarfXmlReader *reader)
Closes parser. Returns 0 or -1 in case of error.

=== CALLBACKS
The main purpose of this library is to interpret data from libxml and assemble them into usable C data structures. When parsing, the library will call the pre-defined callbacks upon completion of parsing an object of their respective type. All parsed data structures are cleared after each callback completes. For this reason it is recomended to only access these structures inside a callback.  If these structures need to be accessed after completion of the callback, see the respective copy method above. All callbacks receive CallbackData as an additional parameter as a context variable. For details on the structure of each individual C struct see the Data Structures section below.

==== typedef void *(*InitialCallback)(Initial *initialData, void *context)
This is called just after the AnalyzerReport start tag is parsed. Returning a non-NULL value will terminate parsing and skip to FinishCallback. InitialData is managed by the parser and therefore should not be altered by the user. If one wishes to alter any fields it is recomended to use the CopyInitial method to obtain a copy that can be written to.

==== typedef void *(*MetricCallback)(Metric *metricData, void *context)
This is called every time a single Metric completes parsing. Returning a non-NULL value will terminate parsing and skip to FinishCallback. MetricData is managed by the parser and therefore should not be altered by the user. If one wishes to alter any fields it is recomended to use the CopyMetric method to obtain a copy that can be written to.

==== typedef void *(*BugCallback)(BugInstance *bugData, void *context)
This is called every time a single BugInstance completes parsing. Returning a non-NULL value will terminate parsing and skip to FinishCallback. BugData is managed by the parser and therefore should not be altered by the user. If one wishes to alter any fields it is recomended to use the CopyBug method to obtain a copy that can be written to.

==== typedef void *(*BugSummaryCallback)(BugSummary *bugSummaryData, void *context)
This is called after all BugSummaries have been parsed. Returning a non-NULL value will terminate parsing and skip to FinishCallback. BugSummaryData is managed by the parser and therefore should not be altered by the user.

==== typedef void *(*MetricSummaryCallback)(MetricSummary *metricSummaryData, void *context)
This is called once all MetricSummaries have been parsed. Returning a non-NULL value will terminate parsing and skip to FinishCallback. MetricSummaryData is managed by the parser and therefore should not be altered by the user.

==== typedef void *(*FinalCallback)(void *returnValue, void *context)
This is called after reaching an AnalayzerReport end tag. If one of the above callbacks terminates parsing with a non-NULL return value, ret is that value, otherwise ret will be NULL.


=== DATA STRUCTURES

The following are the data structures used in the callbacks listed above. Elements that are either not defined or do not exist in the Scarf file will be NULL.

==== typedef struct Initial
----
{
    char *tool_name
    char *tool_version
    char *uuid
} 
----
==== typedef struct BugInstance
----
{
    int bugId
    char *className
    char *bugSeverity
    char *bugRank
    char *resolutionSuggestion
    char *bugMessage
    char *bugCode
    char *bugGroup
    char *assessmentReportFile
    char *buildId
    int *cweIds
    int cweIdsCount
    InstanceLocation instanceLocation
    Method *methods
    int methodsCount
    Location *locations
    int locationsCount
}
----
===== typedef struct InstanceLocation
----
{
    LineNum lineNum
    char *xPath
}
----
====== typedef struct LineNum
----
{
    int start
    int end
}
----
====== typedef struct Method
----
{
    int methodId
    int primary
    char *name
}
----
====== typedef struct Location
----
{
    int primary
    int startLine
    int endLine
    int startColumn
    int endColumn
    int locationId
    char *explanation
    char *sourceFile
}
----
==== typedef struct Metric
----
{
    int id
    char *value
    char *className
    char *methodName
    char *sourceFile
    char *type
}
----

==== typedef struct BugSummary
----
{
    int count
    int byteCount
    char *code
    char *group
    BugSummary *next
}
----

==== typedef struct MetricSummary
----
{
    double count
    double sum
    double sumOfSquares
    double max
    double min
    double stdDeviation
    double average
    int valid
    char *type
    MetricSummary *next
}
----
=== AUTHOR
Brandon Klein
